schema_version: "1.0"
mcp_name: "Lithuanian Law MCP"
jurisdiction: "LT"

sources:
  - name: "TAR Open Data API (Teisės aktų registras)"
    authority: "Seimas of the Republic of Lithuania (Lietuvos Respublikos Seimo kanceliarija)"
    official_portal: "https://www.e-tar.lt"
    retrieval_method: "API"
    update_frequency: "unknown"
    last_ingested: "2026-02-21"
    license_or_terms:
      type: "government_terms"
      url: "https://data.gov.lt/datasets/2613/"
      summary: "Official Lithuanian legal register data is published through the government open-data portal and TAR."
    coverage:
      scope: "All in-force Lithuanian statutes (rusis=Įstatymas, galioj_busena=galioja) available via TAR open-data models."
      limitations: "A small subset of statutes are skipped when no non-empty source text is available or article-level parsing yields no extractable provisions."
    languages:
      - "lt"

  - name: "Lithuanian Open Data Portal"
    authority: "Information Society Development Committee / Government of Lithuania"
    official_portal: "https://data.gov.lt"
    retrieval_method: "API"
    update_frequency: "unknown"
    license_or_terms:
      type: "government_terms"
      url: "https://get.data.gov.lt/datasets/gov/lrsk/teises_aktai/:ns"
      summary: "Machine-readable TAR document and suvestine records, including consolidated legal text fields."
    coverage:
      scope: "Dokumentas and Suvestine models from dataset gov/lrsk/teises_aktai, with Suvestine prioritized and Dokumentas used as fallback."
      limitations: "Model content depends on upstream publication and text availability in each suvestine row; source gaps are documented in data/source/_skipped-laws.json."
    languages:
      - "lt"


data_freshness:
  automated_checks: false
  check_frequency: "manual"
  last_verified: "2026-02-21"
